### ISSUE TITLE
Failed to install with openrefine 3.0

### ISSUE THREAD

**Issue by hekl** [stkenny/grefine-rdf-extension#12]
`console: Failed to install '': java.nio.charset.UnsupportedCharsetException: cp65001.
Exception in thread "main" java.lang.Error: class org.apache.lucene.index.IndexFormatTooOldException: org.apache.lucene.index.IndexFormatTooOldException: Format version is not supported (resource BufferedChecksumIndexInput(MMapIndexInput(path="C:\Users\hlli\AppData\Roaming\OpenRefine\cache\rdfExtension\export\luceneIndex\segments_1"))): -11 (needs to be between 1071082519 and 1071082519). This version of Lucene only supports indexes created with release 5.0 and later.
        at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1777)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:183)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:247)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
        at org.mozilla.javascript.gen.c8._c4(file:/D:/openrefine-3.0/webapp/extensions/module/MOD-INF/controller.js:89)
        at org.mozilla.javascript.gen.c8.call(file:/D:/openrefine-3.0/webapp/extensions/module/MOD-INF/controller.js)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:398)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3065)
        at org.mozilla.javascript.gen.c8.call(file:/D:/openrefine-3.0/webapp/extensions/module/MOD-INF/controller.js)
        at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:636)
        at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94)
        at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)
        at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
        at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
        at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
        at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
        at com.google.refine.RefineServer.configure(Refine.java:296)
        at com.google.refine.RefineServer.init(Refine.java:208)
        at com.google.refine.Refine.init(Refine.java:114)
        at com.google.refine.Refine.main(Refine.java:108)`

**Comment by ettorerizza** [comment]
Hi @hekl, you can go to C:\Users\hlli\AppData\Roaming\OpenRefine\cache\rdfExtension\export\ and simply delete de luceneindex folder.

**Comment by stkenny** [comment]
Hi, yes, there was an upgrade of the Lucene jars which means that the extension won't be compatible with indexes built by previous versions, so you will need to delete the index as @ettorerizza has said.

You will also need to then re-create any RDF file-based reconciliation services that you had added.

**Comment by hekl** [comment]
Thank you! i deleted the the lucene index folder and after a second restart it worked.

**Comment by hekl** [comment]
Works straight away with the openrefine 3.1beta and the new rdf v1.0.1.
