### ISSUE TITLE
Exception on start

### ISSUE THREAD

**Issue by ovillemain** [stkenny/grefine-rdf-extension#14]
With this extension, when I launch OpenRefine it crashes with this error:

> Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException

My (bad ?) solution:
I modified the file "refine".
Before "CLASSPATH=..." (line 564 for OpenRefine 3.1, Linux version), I added this:
>    add_option "--add-modules java.xml.bind"

**Comment by ovillemain** [comment]
My configuration :
- Ubuntu 18.04
- java --version
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)

To reproduce:
1. Download OpenRefine 3.1 : https://github.com/OpenRefine/OpenRefine/releases/download/3.1/openrefine-linux-3.1.tar.gz
2. Installation into /apps/openrefine-3.1
3. Download "RDF extension v1.0.1 for OpenRefine 3.0+" : https://github.com/stkenny/grefine-rdf-extension/releases/download/v1.0.1/grefine-rdf-extension-1.0.1-openrefine-module.zip
4. Create directory : /home/myuser/.local/share/openrefine/extensions/rdf-extension
5. Unzip this extension into this directory.
Now I have that :
/home/myuser/.local/share/openrefine/extensions/rdf-extension/module/...
6. Edit "/apps/openrefine-3.1/refine" to add this parameter "--add-modules java.xml.bind" to the command line

In attach file, it's the result without the parameter.
[withoutparameter.log](https://github.com/stkenny/grefine-rdf-extension/files/2640143/withoutparameter.log)

Thanks.

**Comment by ettorerizza** [comment]
> With this modification, I can launch OpenRefine 3.1 but there is no extension.

Same problem on Windows 10 with OR 3.1. All extensions (even Wikidata) are disabled when I install the RDF extension.

**Comment by stkenny** [comment]
I can reproduce the problem with OpenRefine 3.1 on Ubuntu. I haven't built against 3.1 yet, but I'll do that now. I don't need to make any modification for 3.0 though. That might be related to using OpenJDK 10? There is an open issue with OpenRefine to support JDK 9, so this might be a problem.

**Comment by stkenny** [comment]
The reported exception, 'Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException', does seem to be related to JDK 9 support, see Openrefine/Openrefine#1616

**Comment by kidehen** [comment]
I have a similar issues that produce the following at startup on macOS:
java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

Error:

```
HTTP ERROR 500
Problem accessing /. Reason:

    Butterfly Error
Butterfly incurred in the following errors while initializing:
java.lang.Exception: Failed to initialize module rdf-extension [edu.mit.simile.butterfly.ButterflyModuleImpl]
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:478)
	at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
	at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at com.google.refine.RefineServer.configure(Refine.java:291)
	at com.google.refine.RefineServer.init(Refine.java:203)
	at com.google.refine.Refine.init(Refine.java:109)
	at com.google.refine.Refine.main(Refine.java:103)
Caused by: org.mozilla.javascript.WrappedException: Wrapped org.apache.lucene.index.IndexFormatTooOldException: Format version is not supported (resource BufferedChecksumIndexInput(MMapIndexInput(path="/Users/kidehen/Library/Application Support/OpenRefine/cache/rdfExtension/export/luceneIndex/segments_2m"))): -11 (needs to be between 1071082519 and 1071082519). This version of Lucene only supports indexes created with release 5.0 and later. (file:/Users/kidehen/Library/Application%20Support/OpenRefine/extensions/rdf-extension/module/MOD-INF/controller.js#89)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1932)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.mozilla.javascript.gen.file__Users_kidehen_Library_Application_20Support_OpenRefine_extensions_rdf_extension_module_MOD_INF_controller_js_8._c_init_4(file:/Users/kidehen/Library/Application%20Support/OpenRefine/extensions/rdf-extension/module/MOD-INF/controller.js:89)
	at org.mozilla.javascript.gen.file__Users_kidehen_Library_Application_20Support_OpenRefine_extensions_rdf_extension_module_MOD_INF_controller_js_8.call(file:/Users/kidehen/Library/Application%20Support/OpenRefine/extensions/rdf-extension/module/MOD-INF/controller.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3508)
	at org.mozilla.javascript.gen.file__Users_kidehen_Library_Application_20Support_OpenRefine_extensions_rdf_extension_module_MOD_INF_controller_js_8.call(file:/Users/kidehen/Library/Application%20Support/OpenRefine/extensions/rdf-extension/module/MOD-INF/controller.js)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:636)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94)
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)
	... 8 more
Caused by: org.apache.lucene.index.IndexFormatTooOldException: Format version is not supported (resource BufferedChecksumIndexInput(MMapIndexInput(path="/Users/kidehen/Library/Application Support/OpenRefine/cache/rdfExtension/export/luceneIndex/segments_2m"))): -11 (needs to be between 1071082519 and 1071082519). This version of Lucene only supports indexes created with release 5.0 and later.
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:300)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:286)
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:938)
	at org.deri.grefine.rdf.vocab.imp.VocabularySearcher.<init>(VocabularySearcher.java:74)
	at org.deri.grefine.rdf.app.ApplicationContext.init(ApplicationContext.java:31)
	at org.deri.grefine.rdf.app.InitilizationCommand.initRdfExportApplicationContext(InitilizationCommand.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	... 18 more
```

My folder structure.
<img width="820" alt="screen shot 2018-12-18 at 9 20 58 am" src="https://user-images.githubusercontent.com/1541745/50160072-524b3d00-02a6-11e9-8c1a-21cd8d19cf74.png">

**Comment by jenyoung** [comment]
I am getting the same error as @kidehen above. 

java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

OpenRefine 3.1

Windows 10 Enterprise Version 1803, OS Build 17134.407

RDF Extension v1.1.0


> Problem accessing /. Reason:
> 
>     Butterfly Error
> Butterfly incurred in the following errors while initializing:
> java.lang.Exception: Failed to initialize module rdf-extension [edu.mit.simile.butterfly.ButterflyModuleImpl]
> 	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:478)
> 	at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
> 	at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
> 	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
> 	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
> 	at com.google.refine.RefineServer.configure(Refine.java:291)
> 	at com.google.refine.RefineServer.init(Refine.java:203)
> 	at com.google.refine.Refine.init(Refine.java:109)
> 	at com.google.refine.Refine.main(Refine.java:103)
> Caused by: org.mozilla.javascript.WrappedException: Wrapped org.apache.lucene.index.IndexFormatTooOldException: Format version is not supported (resource BufferedChecksumIndexInput(MMapIndexInput(path="C:\Users\jby568\AppData\Roaming\OpenRefine\cache\rdfExtension\export\luceneIndex\segments_1"))): 0 (needs to be between 4 and 6). This version of Lucene only supports indexes created with release 5.0 and later. (file:/C:/Users/jby568/Desktop/openrefine-win-3.1/openrefine-3.1/webapp/extensions/grefine-rdf-extension-1.1.0-openrefine-module/module/MOD-INF/controller.js#89)
> 	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1932)
> 	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
> 	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
> 	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
> 	at org.mozilla.javascript.gen.file__C__Users_jby568_Desktop_openrefine_win_3_1_openrefine_3_1_webapp_extensions_grefine_rdf_extension_1_1_0_openrefine_module_module_MOD_INF_controller_js_8._c_init_4(file:/C:/Users/jby568/Desktop/openrefine-win-3.1/openrefine-3.1/webapp/extensions/grefine-rdf-extension-1.1.0-openrefine-module/module/MOD-INF/controller.js:89)
> 	at org.mozilla.javascript.gen.file__C__Users_jby568_Desktop_openrefine_win_3_1_openrefine_3_1_webapp_extensions_grefine_rdf_extension_1_1_0_openrefine_module_module_MOD_INF_controller_js_8.call(file:/C:/Users/jby568/Desktop/openrefine-win-3.1/openrefine-3.1/webapp/extensions/grefine-rdf-extension-1.1.0-openrefine-module/module/MOD-INF/controller.js)
> 	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
> 	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3508)
> 	at org.mozilla.javascript.gen.file__C__Users_jby568_Desktop_openrefine_win_3_1_openrefine_3_1_webapp_extensions_grefine_rdf_extension_1_1_0_openrefine_module_module_MOD_INF_controller_js_8.call(file:/C:/Users/jby568/Desktop/openrefine-win-3.1/openrefine-3.1/webapp/extensions/grefine-rdf-extension-1.1.0-openrefine-module/module/MOD-INF/controller.js)
> 	at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:636)
> 	at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94)
> 	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)
> 	... 8 more
> Caused by: org.apache.lucene.index.IndexFormatTooOldException: Format version is not supported (resource BufferedChecksumIndexInput(MMapIndexInput(path="C:\Users\jby568\AppData\Roaming\OpenRefine\cache\rdfExtension\export\luceneIndex\segments_1"))): 0 (needs to be between 4 and 6). This version of Lucene only supports indexes created with release 5.0 and later.
> 	at org.apache.lucene.codecs.CodecUtil.checkHeaderNoMagic(CodecUtil.java:213)
> 	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:302)
> 	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:286)
> 	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:938)
> 	at org.deri.grefine.rdf.vocab.imp.VocabularySearcher.<init>(VocabularySearcher.java:74)
> 	at org.deri.grefine.rdf.app.ApplicationContext.init(ApplicationContext.java:31)
> 	at org.deri.grefine.rdf.app.InitilizationCommand.initRdfExportApplicationContext(InitilizationCommand.java:38)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
> 	... 18 more

![2018-12-19_172444](https://user-images.githubusercontent.com/2250501/50254507-e0f9b000-03b3-11e9-8d78-5406259e8e56.png)
