### ISSUE TITLE
rdfextension issue 

### ISSUE THREAD

**Issue by eliohb** [stkenny/grefine-rdf-extension#20]
Dear,

I have install red extension 1.1.0 and i put all the file in  ..\openrefine-3.1\webapp\extensions
and when i run the program the following error appear:
HTTP ERROR 500
Problem accessing /. Reason:

    Butterfly Error
Butterfly incurred in the following errors while initializing:
java.lang.Exception: Failed to initialize module rdf-extension [edu.mit.simile.butterfly.ButterflyModuleImpl]
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:478)
	at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
	at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at com.google.refine.RefineServer.configure(Refine.java:291)
	at com.google.refine.RefineServer.init(Refine.java:203)
	at com.google.refine.Refine.init(Refine.java:109)
	at com.google.refine.Refine.main(Refine.java:103)
Caused by: org.mozilla.javascript.WrappedException: Wrapped org.apache.lucene.index.IndexFormatTooOldException: Format version is not supported (resource BufferedChecksumIndexInput(MMapIndexInput(path="C:\Users\Toshiba\AppData\Roaming\OpenRefine\cache\rdfExtension\export\luceneIndex\segments_1"))): 0 (needs to be between 4 and 6). This version of Lucene only supports indexes created with release 5.0 and later. (file:/C:/Users/Toshiba/Desktop/openrefine-3.1/webapp/extensions/module/MOD-INF/controller.js#89)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1932)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.mozilla.javascript.gen.file__C__Users_Toshiba_Desktop_openrefine_3_1_webapp_extensions_module_MOD_INF_controller_js_8._c_init_4(file:/C:/Users/Toshiba/Desktop/openrefine-3.1/webapp/extensions/module/MOD-INF/controller.js:89)
	at org.mozilla.javascript.gen.file__C__Users_Toshiba_Desktop_openrefine_3_1_webapp_extensions_module_MOD_INF_controller_js_8.call(file:/C:/Users/Toshiba/Desktop/openrefine-3.1/webapp/extensions/module/MOD-INF/controller.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3508)
	at org.mozilla.javascript.gen.file__C__Users_Toshiba_Desktop_openrefine_3_1_webapp_extensions_module_MOD_INF_controller_js_8.call(file:/C:/Users/Toshiba/Desktop/openrefine-3.1/webapp/extensions/module/MOD-INF/controller.js)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:636)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94)
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)
	... 8 more
Caused by: org.apache.lucene.index.IndexFormatTooOldException: Format version is not supported (resource BufferedChecksumIndexInput(MMapIndexInput(path="C:\Users\Toshiba\AppData\Roaming\OpenRefine\cache\rdfExtension\export\luceneIndex\segments_1"))): 0 (needs to be between 4 and 6). This version of Lucene only supports indexes created with release 5.0 and later.
	at org.apache.lucene.codecs.CodecUtil.checkHeaderNoMagic(CodecUtil.java:213)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:302)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:286)
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:938)
	at org.deri.grefine.rdf.vocab.imp.VocabularySearcher.<init>(VocabularySearcher.java:74)
	at org.deri.grefine.rdf.app.ApplicationContext.init(ApplicationContext.java:31)
	at org.deri.grefine.rdf.app.InitilizationCommand.initRdfExportApplicationContext(InitilizationCommand.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	... 18 more
any advice

**Comment by stkenny** [comment]
Hi, you will need to remove the folder C:\Users\Toshiba\AppData\Roaming\OpenRefine\cache\rdfExtension\export\luceneIndex
See https://github.com/stkenny/grefine-rdf-extension#issues

**Comment by eliohb** [comment]
I have removed the folder but the RDF extension is gone now

**Comment by eliohb** [comment]
I have removed the folder and then i run the .exe file the folder removed have been reated egain and the rdf extension don't appear any more

**Comment by stkenny** [comment]
Is there another error in the log? What java version are you using? Thanks.

**Comment by eliohb** [comment]
java 1.8.0-191

**Comment by stkenny** [comment]
I've installed OpenRefine 3.1, with the RDF extension release 1.1.0, and JRE 1.8 on Windows 10 and was not able to reproduce. Is it possible that you have some old extensions from previous OpenRefine versions still installed in a workspace that are causing problems?
