### ISSUE TITLE
Support JDK 9+

### ISSUE THREAD

**Issue by stkenny** [stkenny/grefine-rdf-extension#24]
> Hi, it looks like maybe the source code of the extension is in the extension folder rather than the compiled release? Could you install from https://github.com/stkenny/grefine-rdf-extension/releases/download/v1.1.0/grefine-rdf-extension-1.1.0-openrefine-module.zip instead. Remove the contents of the rdf-extension folder and replace with the extracted contents of the zip.

I replaced the file, but encountered another error.
```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at org.apache.tika.config.TikaConfig.<init>(TikaConfig.java:161)
        at org.apache.tika.config.TikaConfig.<init>(TikaConfig.java:151)
        at org.apache.tika.config.TikaConfig.<init>(TikaConfig.java:144)
        at org.apache.tika.config.TikaConfig.<init>(TikaConfig.java:140)
        at org.apache.any23.mime.TikaMIMETypeDetector.<init>(TikaMIMETypeDetector.java:204)
        at org.apache.any23.Any23.<init>(Any23.java:83)
        at org.apache.any23.Any23.<init>(Any23.java:130)
        at org.apache.any23.Any23.<init>(Any23.java:154)
        at org.apache.any23.Any23.<init>(Any23.java:161)
        at org.deri.grefine.rdf.vocab.VocabularyImporter.getModel(VocabularyImporter.java:75)
        at org.deri.grefine.rdf.vocab.VocabularyImporter.importVocabulary(VocabularyImporter.java:30)
        at org.deri.grefine.rdf.vocab.imp.VocabularySearcher.importAndIndexVocabulary(VocabularySearcher.java:90)
        at org.deri.grefine.rdf.vocab.imp.VocabularySearcher.importAndIndexVocabulary(VocabularySearcher.java:82)
        at org.deri.grefine.rdf.vocab.imp.PredefinedVocabularyManager.addPredefinedVocabularies(PredefinedVocabularyManager.java:71)
        at org.deri.grefine.rdf.vocab.imp.PredefinedVocabularyManager.<init>(PredefinedVocabularyManager.java:46)
        at org.deri.grefine.rdf.app.ApplicationContext.init(ApplicationContext.java:32)
        at org.deri.grefine.rdf.app.InitilizationCommand.initRdfExportApplicationContext(InitilizationCommand.java:38)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
        at org.mozilla.javascript.gen.file__D__MoreProgram_openrefine_3_1_webapp_extensions_rdf_extension_module_MOD_INF_controller_js_8._c_init_4(file:/D:/MoreProgram/openrefine-3.1/webapp/extensions/rdf-extension/module/MOD-INF/controller.js:89)
        at org.mozilla.javascript.gen.file__D__MoreProgram_openrefine_3_1_webapp_extensions_rdf_extension_module_MOD_INF_controller_js_8.call(file:/D:/MoreProgram/openrefine-3.1/webapp/extensions/rdf-extension/module/MOD-INF/controller.js)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3508)
        at org.mozilla.javascript.gen.file__D__MoreProgram_openrefine_3_1_webapp_extensions_rdf_extension_module_MOD_INF_controller_js_8.call(file:/D:/MoreProgram/openrefine-3.1/webapp/extensions/rdf-extension/module/MOD-INF/controller.js)
        at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:636)
        at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94)
        at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)
        at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
        at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
        at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
        at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
        at com.google.refine.RefineServer.configure(Refine.java:291)
        at com.google.refine.RefineServer.init(Refine.java:203)
        at com.google.refine.Refine.init(Refine.java:109)
        at com.google.refine.Refine.main(Refine.java:103)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at edu.mit.simile.butterfly.ButterflyClassLoader.loadClass(ButterflyClassLoader.java:65)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 40 more
```

I have solved the error by changing the jdk version from 1.9.0 to 1.8.0. Thank you!

_Originally posted by @Liuyan661 in https://github.com/stkenny/grefine-rdf-extension/issues/23#issuecomment-479709923_

**Comment by stkenny** [comment]
any23 was removed as a dependency
