### ISSUE TITLE
fail to add rdf extension

### ISSUE THREAD

**Issue by xueli-pan** [stkenny/grefine-rdf-extension#40]
Hello. I failed to add rdf extension (OpenRefine 3.3 v1.2.0) with the following error. I followed the instructions to add a new folder named rdf-extension but still failed.

Is there anyone who could help me with the problem?
Thanks in advance!

Best,
Sherry

![image](https://user-images.githubusercontent.com/54152377/83362811-600a5a80-a394-11ea-91e1-bb6688585ce3.png)

HTTP ERROR 500
Problem accessing /. Reason:

    Butterfly Error
Butterfly incurred in the following errors while initializing:
java.lang.Exception: Failed to initialize module rdf-extension [edu.mit.simile.butterfly.ButterflyModuleImpl]
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:478)
	at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
	at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at com.google.refine.RefineServer.configure(Refine.java:291)
	at com.google.refine.RefineServer.init(Refine.java:203)
	at com.google.refine.Refine.init(Refine.java:109)
	at com.google.refine.Refine.main(Refine.java:103)
Caused by: org.mozilla.javascript.EvaluatorException: Can't find method com.google.refine.RefineServlet.cacheClass(object). (file:/Users/sherry/Library/Application%20Support/OpenRefine/extensions/rdf-extension/src/main/resources/module/MOD-INF/controller.js#82)
	at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:77)
	at org.mozilla.javascript.Context.reportRuntimeError(Context.java:998)
	at org.mozilla.javascript.Context.reportRuntimeError(Context.java:1053)
	at org.mozilla.javascript.Context.reportRuntimeError1(Context.java:1016)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:144)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.mozilla.javascript.gen.file__Users_sherry_Library_Application_20Support_OpenRefine_extensions_rdf_extension_src_main_resources_module_MOD_INF_controller_js_10._c_init_4(file:/Users/sherry/Library/Application%20Support/OpenRefine/extensions/rdf-extension/src/main/resources/module/MOD-INF/controller.js:82)
	at org.mozilla.javascript.gen.file__Users_sherry_Library_Application_20Support_OpenRefine_extensions_rdf_extension_src_main_resources_module_MOD_INF_controller_js_10.call(file:/Users/sherry/Library/Application%20Support/OpenRefine/extensions/rdf-extension/src/main/resources/module/MOD-INF/controller.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3508)
	at org.mozilla.javascript.gen.file__Users_sherry_Library_Application_20Support_OpenRefine_extensions_rdf_extension_src_main_resources_module_MOD_INF_controller_js_10.call(file:/Users/sherry/Library/Application%20Support/OpenRefine/extensions/rdf-extension/src/main/resources/module/MOD-INF/controller.js)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:636)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94)
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)
	... 8 more

**Comment by stkenny** [comment]
Hi, sorry for the late response. That looks like you have downloaded the source, not the compiled extension. Can you make sure you have download and extracted https://github.com/stkenny/grefine-rdf-extension/releases/download/v1.2.0-orefine-3.3/rdf-extension-1.2.0-orefine-3.3.zip to the folder.

**Comment by RolfBly** [comment]
Hi, I had the same problem (and solution) as the OP, due to the fact that the rdf-extension _is named_ "OpenRefine v 1.3.1" on the [readme page](https://github.com/stkenny/grefine-rdf-extension#latest-release). "That's not what I want, I already have that", I thought, and then I downloaded the zip. It would be clearer if it were named "RDF-extension v x.x.x".
