### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by MPParsley** [stkenny/grefine-rdf-extension#65]
Hi, thanks for this extension.

I tried installing this extension in both in both ways as described is described on https://docs.openrefine.org/manual/installing#installing-extensions
- in webapp/extensions/rdf-extension
- in ~/.local/share/openrefine/extensions/rdf-extension

The latter doesn't change anything and the first results in the following error:
```
HTTP ERROR 500 Butterfly Error Butterfly incurred in the following errors while initializing: java.lang.Exception: Failed to initialize module: rdf-extension [edu.mit.simile.butterfly.ButterflyModuleImpl] at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:478) at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451) at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308) at org.eclipse.jetty.servlet.ServletHolder$WrapperServlet.init(ServletHolder.java:1281) at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:594) at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:478) at org.eclipse.jetty.servlet.ServletHolder.prepare(ServletHolder.java:720) at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:590) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607) at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297) at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485) at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577) at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) at org.eclipse.jetty.server.Server.handle(Server.java:500) at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547) at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270) at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:829) Caused by: org.mozilla.javascript.WrappedException: Wrapped java.nio.file.AccessDeniedException: /home/openrefine (file:/opt/openrefine/webapp/extensions/rdf-extension/module/MOD-INF/controller.js#89) at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1825) at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:227) at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:211) at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:35) at org.mozilla.javascript.gen.file__opt_openrefine_webapp_extensions_rdf_extension_module_MOD_INF_controller_js_10._c_init_4(file:/opt/openrefine/webapp/extensions/rdf-extension/module/MOD-INF/controller.js:89) at org.mozilla.javascript.gen.file__opt_openrefine_webapp_extensions_rdf_extension_module_MOD_INF_controller_js_10.call(file:/opt/openrefine/webapp/extensions/rdf-extension/module/MOD-INF/controller.js) at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:380) at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3868) at org.mozilla.javascript.gen.file__opt_openrefine_webapp_extensions_rdf_extension_module_MOD_INF_controller_js_10.call(file:/opt/openrefine/webapp/extensions/rdf-extension/module/MOD-INF/controller.js) at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:636) at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94) at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476) ... 32 more Caused by: java.nio.file.AccessDeniedException: /home/openrefine at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) at java.base/java.nio.file.Files.createDirectory(Files.java:690) at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:797) at java.base/java.nio.file.Files.createDirectories(Files.java:783) at org.apache.lucene.store.FSDirectory.<init>(FSDirectory.java:157) at org.apache.lucene.store.MMapDirectory.<init>(MMapDirectory.java:159) at org.apache.lucene.store.MMapDirectory.<init>(MMapDirectory.java:112) at org.apache.lucene.store.FSDirectory.open(FSDirectory.java:197) at org.apache.lucene.store.FSDirectory.open(FSDirectory.java:190) at org.deri.grefine.rdf.vocab.imp.VocabularySearcher.<init>(VocabularySearcher.java:72) at org.deri.grefine.rdf.app.ApplicationContext.init(ApplicationContext.java:30) at org.deri.grefine.rdf.app.InitializationCommand.initRdfExportApplicationContext(InitializationCommand.java:36) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:566) at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:206) ... 42 more
URI:	/
STATUS:	500
MESSAGE:	Butterfly Error Butterfly incurred in the following errors while initializing: java.lang.Exception: Failed to initialize module: rdf-extension [edu.mit.simile.butterfly.ButterflyModuleImpl] at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:478) at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451) at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308) at org.eclipse.jetty.servlet.ServletHolder$WrapperServlet.init(ServletHolder.java:1281) at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:594) at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:478) at org.eclipse.jetty.servlet.ServletHolder.prepare(ServletHolder.java:720) at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:590) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607) at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297) at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485) at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577) at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) at org.eclipse.jetty.server.Server.handle(Server.java:500) at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547) at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270) at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:829) Caused by: org.mozilla.javascript.WrappedException: Wrapped java.nio.file.AccessDeniedException: /home/openrefine (file:/opt/openrefine/webapp/extensions/rdf-extension/module/MOD-INF/controller.js#89) at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1825) at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:227) at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:211) at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:35) at org.mozilla.javascript.gen.file__opt_openrefine_webapp_extensions_rdf_extension_module_MOD_INF_controller_js_10._c_init_4(file:/opt/openrefine/webapp/extensions/rdf-extension/module/MOD-INF/controller.js:89) at org.mozilla.javascript.gen.file__opt_openrefine_webapp_extensions_rdf_extension_module_MOD_INF_controller_js_10.call(file:/opt/openrefine/webapp/extensions/rdf-extension/module/MOD-INF/controller.js) at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:380) at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3868) at org.mozilla.javascript.gen.file__opt_openrefine_webapp_extensions_rdf_extension_module_MOD_INF_controller_js_10.call(file:/opt/openrefine/webapp/extensions/rdf-extension/module/MOD-INF/controller.js) at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:636) at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94) at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476) ... 32 more Caused by: java.nio.file.AccessDeniedException: /home/openrefine at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) at java.base/java.nio.file.Files.createDirectory(Files.java:690) at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:797) at java.base/java.nio.file.Files.createDirectories(Files.java:783) at org.apache.lucene.store.FSDirectory.<init>(FSDirectory.java:157) at org.apache.lucene.store.MMapDirectory.<init>(MMapDirectory.java:159) at org.apache.lucene.store.MMapDirectory.<init>(MMapDirectory.java:112) at org.apache.lucene.store.FSDirectory.open(FSDirectory.java:197) at org.apache.lucene.store.FSDirectory.open(FSDirectory.java:190) at org.deri.grefine.rdf.vocab.imp.VocabularySearcher.<init>(VocabularySearcher.java:72) at org.deri.grefine.rdf.app.ApplicationContext.init(ApplicationContext.java:30) at org.deri.grefine.rdf.app.InitializationCommand.initRdfExportApplicationContext(InitializationCommand.java:36) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:566) at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:206) ... 42 more
SERVLET:	refine
```

I'm using OpenRefine 3.4.

What am I missing?

**Comment by MPParsley** [comment]
Update: option 1 works but it has to be under the user that is running openrefine in /etc/systemd/system/openrefine.service:

```
[Unit]
Description=OpenRefine
[Service]
User=openrefine
ExecStart=/opt/openrefine/refine -i 0.0.0.0 -m 3G
TimeoutStopSec=3600s
Restart=always
RestartSec=10
[Install]
WantedBy=default.target
```

Not sure why the other approach isn't working though.
